### ISSUE TITLE
Ampersands in Terraform Outputs are being Encoded

### ISSUE THREAD

**Issue by martinpeck** [getporter/terraform-mixin#94] opened 2022-09-07 13:45 UTC
Hi there,

In PR #91 there was a change to the way that this mixin grabs output from Terraform. Specifically, the mixin now requests output values as `json` rather than `raw` format. Here is the change in question:

https://github.com/getporter/terraform-mixin/pull/91/files#diff-282757e263fe02ec96e35fd1120b9263db1ca315d75cea25d3ccf68239bd7472L56

Unfortunately, due to some strange formatting rules within Terraform, this breaks any URI that includes an ampersand (i.e. URIs or URLs that have querystring parameters) and this is a common case for connection strings or service endpoints.

My investigation into an issue has been written up here, and includes a small repro sample that demonstrates the issue: 
https://github.com/microsoft/AzureTRE/issues/2549#issuecomment-1239341427

There is a closed Terraform issue describes this behaviour  and it was closed by simply adding additional documentation to explain the behaviour (and a comment that they will never change this behaviour):
https://github.com/hashicorp/terraform/issues/26110

The fix was to better document it:
https://github.com/hashicorp/terraform/pull/26122

Can the terraform-mixin either switch back to using the `-raw` flag when accessing TF outputs? I'm not sure what the alternative is (I'm not sure how safe it would be to patch up/replace these encoded characters)

**Comment by martinpeck** [comment] 2022-09-09 16:28
A conversation about this issue has taken place on the Terraform repo.

The following are the most useful comments:
https://github.com/hashicorp/terraform/issues/31756#issuecomment-1241378444
https://github.com/hashicorp/terraform/issues/31756#issuecomment-1242155295

The point made in these comments is that it's not a valid use of the `-json` format switch to take JSON output from Terraform and then parse it as a string, rather than as JSON.

A suggested (untested) code fix has been given that might allow the outputs to be inspected, for true JSON output to then be returned as JSON, but for other output (regular strings) to be returned as their raw value.

**Comment by martinpeck** [comment] 2022-09-09 16:36
The use of the `-raw` switch within this mixin means that JSON encoded strings are being passed as outputs from the bundle, but they are being treated as regular strings. In the case where that string has an ampersand it results in an encoded ampersand being passed back.

**Comment by carolynvs** [comment] 2022-09-09 17:17
@martinpeck Thanks for the the background on the problem and apologies for the regression. It's a bit to digest but I'm sure we can get this fixed in the mixin with all the great info from the other issue's comments.

If you are up for trying a PR, great! Otherwise I'll keep it at the top of our backlog and will try to get it fixed in the 1.0 release of the mixin.

**Comment by martinpeck** [comment] 2022-09-09 18:10
Thanks @carolynvs. I'll take a look next week and see if I can PR a fix for this.

I'll also take a look at the reasoning behind the switch from `-raw` to `-json`, but if you have some context as to why that change was made that might he helpful when it comes to testing.

**Comment by carolynvs** [comment] 2022-09-09 18:56
@sgettys can provide more detail, here is the [original issue](https://github.com/getporter/terraform-mixin/pull/89) and [PR](https://github.com/getporter/terraform-mixin/pull/91) that prompted the switch

**Comment by sgettys** [comment] 2022-09-09 20:35
The reason for the switch from -raw to -json is because -raw doesn't support complex object types for the output, only string, bool, and number. I've moved over to doing proper JSON unmarshaling for the output string to essentially rip off the json encoding put on there by Terraform. I'll be adding in some more tests to make sure we're not missing another regression for this, thanks for finding and detailing this bug!

**Comment by martinpeck** [comment] 2022-09-09 21:59
That's awesome @sgettys ! 
Thanks!

**Closed** 2022-09-14 17:07 UTC
Labels: bug, 1 - 🍫

**Comment by martinpeck** [comment] 2022-09-15 07:52
Thanks @sgettys , @VinozzZ , @carolynvs ! Really appreciate the quick turn around.

Can you let me know roughly when this might appear in a release? I'd like to pick this change up for a project I'm working on right now, if possible.

**Comment by carolynvs** [comment] 2022-09-15 13:02
I am fixing a bug in the mixins today and then cutting new release candidates of everything. You can always build the mixin locally with `mage build` and then install it into your PORTER_HOME directory with `mage install` until an updated release candidate is available.

**Comment by carolynvs** [comment] 2022-09-22 19:43
I recommend installing porter v1.0.0-rc.2 and then install the terraform mixin with `porter mixins install terraform --version v1.0.0-rc.1`.

The new versions of the mixins _probably_ work with v0 still but really I have never tried. They are intended to work with porter v1.

**Comment by martinpeck** [comment] 2022-09-22 19:46
Out of interest...for a fresh install of everything, how does porter determine which mixin versions to install?

**Comment by carolynvs** [comment] 2022-09-22 21:50
Just in case anyone else is wondering, here's how it works.

Previously Porter v0 installed a bunch of extra mixins. Now Porter v1's install script only installs porter and the exec mixin (the same version as porter, since they are in the same repo). All other mixins must be explicitly installed.

Also the `porter mixins install` command installs only the latest _stable_ version which excludes these pre-release versions of the mixins. So you have to explicitly pick the version when installing a pre-release mixin with the --version flag.
