### ISSUE TITLE
can't cd into /cnab/app/terraform -- is it no longer created?

### ISSUE THREAD

**Issue by squillace** [getporter/terraform-mixin#63] opened 2021-05-25 17:34 UTC
I'm wondering whether terraform creates this directory now? What changed? any ideas, @vdice or @carolynvs ?

https://github.com/squillace/blowschunks is a bundle; what happens when you build with porter v0.38.1 (3018b91c) is: 

```
Writing Dockerfile =======>
FROM debian:stretch-slim

ARG BUNDLE_DIR

RUN apt-get update && apt-get install -y ca-certificates

ENV TERRAFORM_VERSION=0.12.17
RUN apt-get update && apt-get install -y wget unzip && \
 wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
 unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin
COPY . $BUNDLE_DIR
RUN cd /cnab/app/terraform && terraform init -backend=false

# exec mixin has no buildtime dependencies


COPY . $BUNDLE_DIR
RUN rm $BUNDLE_DIR/porter.yaml
RUN rm -fr $BUNDLE_DIR/.cnab
COPY .cnab /cnab
WORKDIR $BUNDLE_DIR
CMD ["/cnab/app/run"]

Starting Invocation Image Build (getporter/porter-hello-installer:v0.1.0) =======>
Step 1/13 : FROM debian:stretch-slim
 ---> 546475075b6c
Step 2/13 : ARG BUNDLE_DIR
 ---> Using cache
 ---> dbf5a3ec6635
Step 3/13 : RUN apt-get update && apt-get install -y ca-certificates
 ---> Using cache
 ---> f9d60b6f9aaa
Step 4/13 : ENV TERRAFORM_VERSION=0.12.17
 ---> Using cache
 ---> 368b927d60b9
Step 5/13 : RUN apt-get update && apt-get install -y wget unzip &&  wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip &&  unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin
 ---> Using cache
 ---> ec088e537dc8
Step 6/13 : COPY . $BUNDLE_DIR
 ---> Using cache
 ---> e883b594938d
Step 7/13 : RUN cd /cnab/app/terraform && terraform init -backend=false
 ---> Running in d6badbe616b0
/bin/sh: 1: cd: can't cd to /cnab/app/terraform
Error: unable to build CNAB invocation image: failed to stream docker build output: The command '/bin/sh -c cd /cnab/app/terraform && terraform init -backend=false' returned a non-zero code: 2
```

**Comment by carolynvs** [comment] 2021-05-26 15:04
Closing as a duplicate of #62. Per #62 we should validate that the terraform configuration directory exists. On top of that, it would be great to make the directory configurable per #16.

**Closed by carolynvs** 2021-05-26 15:04 UTC
